@istest
public class custommetadata {

    
    @istest
    public static   void abbcc()
    {
   /*          
        // Step 1: Create the CustomMetadata object
        Metadata.CustomMetadata cmd = new Metadata.CustomMetadata();
        // Important: 
        // Full name format = metadata type name + DeveloperName
        cmd.fullName = 'metadddata__mdt.My_Custom_Metadata_Record2'; // Create record "My_Custom_Metadata_Record"
        cmd.label = 'My Custom Metadata Record2'; // Label field (required)
        // Step 2: Set the field value for car_c__c
        Metadata.CustomMetadataValue carField = new Metadata.CustomMetadataValue();
        carField.field = 'cool__c';  // Field API Name exactly
        carField.value = 'BMW45554';        // Example value you want to insert
        // Step 3: Attach field values
        cmd.values = new List<Metadata.CustomMetadataValue> { carField };
        // Step 4: Create deploy container and add this record
        Metadata.DeployContainer mdContainer = new Metadata.DeployContainer();
        mdContainer.addMetadata(cmd);  
        // Step 5: Deploy using enqueueDeployment
        Id jobId = Metadata.Operations.enqueueDeployment(mdContainer, null);    
        System.debug('Deployment Job Id: ' + jobId);
*/
    }
}