public class futuremethodcount {

    public static integer i =0;
    @future
    public static void future1()
    {
        system.debug('future !!11');
    }
     @future
    public static void future2()
    {
        system.debug('future !!11');
    }
     @future
    public static void future3()
    {
        system.debug('future !!11');
    }
     @future
    public static void future4()
    {
        system.debug('future !!11');
    }
}